FROM python:3.10

WORKDIR /code

# Install Flower and other dependencies
RUN pip install flower

# Copy your Django project code into the container
COPY . /code

# Set the entrypoint command
CMD flower --broker=redis://redis:6379/0
