# Generated by Django 4.2.2 on 2023-10-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopnest", "0003_order_order_number_order_order_status_and_more"),
        ("authentication", "0002_remove_userprofile_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="payment_methods",
            field=models.ManyToManyField(blank=True, to="shopnest.paymentmethod"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="prime_member",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recommended_categories",
            field=models.ManyToManyField(blank=True, to="shopnest.category"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reviews_and_ratings",
            field=models.ManyToManyField(
                through="shopnest.ReviewAndRating", to="shopnest.product"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shipping_addresses",
            field=models.ManyToManyField(blank=True, to="shopnest.shippingaddress"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="shopping_lists",
            field=models.ManyToManyField(
                blank=True, related_name="shoppers", to="shopnest.wishlist"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="wishlists",
            field=models.ManyToManyField(blank=True, to="shopnest.wishlist"),
        ),
    ]
